### ISSUE TITLE
[Question] Has this been tested on Pytorch 2.0?

### ISSUE THREAD

**Issue by MyronRodrigues-StreetDrone** [Haiyang-W/DSVT#11]
Hey thanks for open sourcing your work.

Leaving this question here so people can see/answer if anyone tests this on Pytorch 2.0

**Comment by chenshi3** [comment]
We do not test the code on Pytorch 2.0, and we use  Pytorch 1.9.1

**Comment by Haiyang-W** [comment]
You can try to be compatible with PyTorch 2.0, which will make model training faster.

**Comment by YoushaaMurhij** [comment]
It works fine with Pytorch 2.0.0

**Comment by Haiyang-W** [comment]
Great!

**Comment by MyronRodrigues-StreetDrone** [comment]
thanks @YoushaaMurhij
