### ISSUE TITLE
Error about setup.py

### ISSUE THREAD

**Issue by Doctor-James** [Haiyang-W/DSVT#13]
Congratulations on being accepted by CVPR！
I got lots of 'invalid static_cast' error when I execute 'python setup.py install'
my env torch == 1.13.0+cu117 ,CUDA Version: 11.7 
Once I annotated the following code in setup.py, the installation was complete，which means the error is in ingroup_inds_cuda
`            make_cuda_ext(
                name='ingroup_inds_cuda',
                module='pcdet.ops.ingroup_inds',
                sources=[
                    'src/ingroup_inds.cpp',
                    'src/ingroup_inds_kernel.cu',
                ]`
Maybe it's my pytorch version, but the versions you recommended below torch1.10 don't fit my cuda version 11.7，Since I don't have sudo permission, it's difficult to change the cuda version.

Could you please see if there is any solution？Thanks！

**Comment by Haiyang-W** [comment]
sorry for the late reply. 
This may not be CUDA's problem. You can try to directly install torch1.10 by "pip install torch==1.10.0+cu111 torchvision==0.11.0+cu111 torchaudio==0.10.0 -f https://download.pytorch.org/whl/torch_stable.html". 
CUDA 11.7 is backward compatible with CUDA 11.1.
