### ISSUE TITLE
Question about pytorch version

### ISSUE THREAD

**Issue by sky-fly97** [Haiyang-W/DSVT#15]
Hello, my pytorch version is 1.8.1, I encountered this problem while training, does the pytorch version have to be higher than 1.9.0?
`../pcdet/models/backbones_3d/dsvt.py", line 212, in __init__ 
self.self_attn = nn.MultiheadAttention(d_model, nhead, dropout=dropout, batch_first=batch_first)
TypeError: __init__() got an unexpected keyword argument 'batch_first'`

**Comment by Haiyang-W** [comment]
yes, please try Pytorch 1.10. MultiheadAttention may be different between 1.8 and 1.10.
