### ISSUE TITLE
Any plan to release tensorrt convert codes?

### ISSUE THREAD

**Issue by elliotzheng** [Haiyang-W/DSVT#17]
Good work! Any plan to release tensorrt convert codes?

**Comment by chenshi3** [comment]
Yes, we will provide some detailed instructions for convert codes to tensorrt engine in the near future. We are rushing for some deadlines lately, so it may take a little more time.

**Comment by elliotzheng** [comment]
> Yes, we will provide some detailed instructions for converting codes to tensorrt engine in the near future. We are rushing for some deadlines lately, so it may take a little more time.

Thank you, looking forward to that! :)
