### ISSUE TITLE
Question about DSVT-P on waymo

### ISSUE THREAD

**Issue by sky-fly97** [Haiyang-W/DSVT#18]
In paper B.1.1，it is mentioned here that both DSVT-P and DSVT-V have 4 DSVT blocks, but it seems that `dsvt_models/dsvt_plain_1f_onestage.yaml` is only 1 block.

**Comment by Haiyang-W** [comment]
you can refer [config](https://github.com/Haiyang-W/DSVT/blob/67b71f578457a3bd1240ebad3aeb68f6060378f2/tools/cfgs/dsvt_models/dsvt_plain_1f_onestage.yaml#L78). The set info is 36, 4, indicating 4 blocks. You can print the model architecture by running the code.
