### ISSUE TITLE
您好，我在国内，流量不多，只够下载一份数据集，请问我应该下载哪个版本的waymo Perception数据集，OpenPCDet可以处理waymo所有版本的数据集吗？

### ISSUE THREAD

**Issue by ZoangX** [Haiyang-W/DSVT#19]

**Comment by Haiyang-W** [comment]
Hi, if you are in the china mainland, you can download waymo data by [OpenDataLab](https://opendatalab.com/Waymo). I think the latest version of waymo 3D Object Detection is fine.

**Comment by ZoangX** [comment]
> Hi, if you are in the china mainland, you can download waymo data by [OpenDataLab](https://opendatalab.com/Waymo). I think the latest version of waymo 3D Object Detection is fine.

Thank you very much! I will try it.

**Comment by Haiyang-W** [comment]
> > Hi, if you are in the china mainland, you can download waymo data by [OpenDataLab](https://opendatalab.com/Waymo). I think the latest version of waymo 3D Object Detection is fine.
> 
> Thank you very much! I will try it.
Can [OpenDataLab](https://opendatalab.com/Waymo)  be downloaded? Waymo only actually has about 1T PC data for lidar-only 3D object detection, but it seems to have everything (about 5T). But anyway, it downloads really fast. I haven't tried to download Waymo, I've downloaded COCO, about 20M/s on my server.

**Comment by ZoangX** [comment]
> > > Hi, if you are in the china mainland, you can download waymo data by [OpenDataLab](https://opendatalab.com/Waymo). I think the latest version of waymo 3D Object Detection is fine.
> > 
> > 
> > Thank you very much! I will try it.
> 
> Can [OpenDataLab](https://opendatalab.com/Waymo) be downloaded? Waymo only actually has about 1T PC data for lidar-only 3D object detection, but it seems to have everything (about 5T). But anyway, it downloads really fast. I haven't tried to download Waymo, I've downloaded COCO, about 20M/s on my server.

opendatalab下载是能下载，但是数据量太大了，5个T，他们没有把motion和perception分开，更别说perception里训练集和数据集的划分了，我联系了opendatalab的技术支持，他们说会再重新上传一边，但是得等到劳动节之后了，难受的一匹。

**Comment by Haiyang-W** [comment]
> > > > Hi, if you are in the china mainland, you can download waymo data by [OpenDataLab](https://opendatalab.com/Waymo). I think the latest version of waymo 3D Object Detection is fine.
> > > 
> > > 
> > > Thank you very much! I will try it.
> > 
> > 
> > Can [OpenDataLab](https://opendatalab.com/Waymo) be downloaded? Waymo only actually has about 1T PC data for lidar-only 3D object detection, but it seems to have everything (about 5T). But anyway, it downloads really fast. I haven't tried to download Waymo, I've downloaded COCO, about 20M/s on my server.
> 
> opendatalab下载是能下载，但是数据量太大了，5个T，我们实验室的数据盘才4T，他们没有把motion和perception分开，更别说perception里训练集和数据集的划分了，我联系了opendatalab的技术支持，他们说会再重新上传一边，但是得等到劳动节之后了，难受的一匹。

很棒！如果能重新上传，国内使用waymo会方便非常非常多，之前下载waymo花了至少两三个周（下载到本地+上传到服务器）。有了opendatalab就可以直接在服务器上下载了，方便非常多。

祝你顺利！
