### ISSUE TITLE
GPU memory size

### ISSUE THREAD

**Issue by skprot** [Haiyang-W/DSVT#23]
Thanks for your incredible work! 
1. I'm wondering how much minimum GPU memory should be in my setup to run training? 
2. I also did not find information in the article how much GPU memory should be for model inference?

**Comment by Haiyang-W** [comment]
Hi, 
1. If you use DSVT-P, batch size = 1 and fp16, It only requires 9GB for Training. 
2. All inference variants are fp32, and require about 3~4GB GPU memory.
