### ISSUE TITLE
Question about the CT3D-based two-stage DSVT on WOD training yaml file

### ISSUE THREAD

**Issue by ylwhxht** [Haiyang-W/DSVT#24]
Thanks for your excellent work, I wanted to reproduce the experimental results of the two-stage DSVT-TS on waymo's 100% training set, but I did not find the relevant two-stage configuration file with CT3D as the model, all of which are the first-stage configuration files with CenterPoint as the model. 

Can you upload or tell me where it is? 

Thank you very much

**Comment by chenshi3** [comment]
Sorry for the late reply. Regarding the training of our two-stage model, we fix the 1st-stage DSVT model and only finetune the 2nd-stage refinement module for 12 epochs with the same training schedule.  The process is a bit complex and detailed, we may not release it.  However, if you require it urgently, please feel free to send me an email.

**Comment by Haiyang-W** [comment]
> Thanks for your excellent work, I wanted to reproduce the experimental results of the two-stage DSVT-TS on waymo's 100% training set, but I did not find the relevant two-stage configuration file with CT3D as the model, all of which are the first-stage configuration files with CenterPoint as the model.
> 
> Can you upload or tell me where it is?
> 
> Thank you very much

Please give me your email. I will give you an unrefined CT3D-based two-stage code in a few days as soon as possible. :)

Haiyang

**Comment by zizhengu** [comment]
> 
Hi! Thank you very much for your previous help and patience. I have achieved excellent results in my task with your amazing DSVT model. 
I would like to try the two-stage model further. Could you please send me the  CT3D-based code ? Thanks again! Also, I would like to know if the two-stage model would significantly slow down the inference speed.
Here is my email: [zizhengu@163.com](mailto:zizhengu@163.com)

**Comment by Haiyang-W** [comment]
> > 
> 
> Hi! Thank you very much for your previous help and patience. I have achieved excellent results in my task with your amazing DSVT model. I would like to try the two-stage model further. Could you please send me the CT3D-based code ? Thanks again! Also, I would like to know if the two-stage model would significantly slow down the inference speed. Here is my email: [zizhengu@163.com](mailto:zizhengu@163.com)

Have sent it to email! :)

**Comment by Zhaoguanhua** [comment]
hello, Could you send me the CT3D-based two-stage code? 
my email: a18707199526@163.com
