### ISSUE TITLE
Waymo open dataset evaluation too slow.

### ISSUE THREAD

**Issue by synsin0** [Haiyang-W/DSVT#26]
I encountered too slow evaluation process of WOD using waymo metrics. This issue seems a common issue for openpcdet. If I switch to kitti metrics it runs to OOM (RAM:120G). I wonder whether you may provide some instructions.

**Comment by Haiyang-W** [comment]
In my experiment, the evaluation of waymo is only ~20 min. 

The evaluation time is often too much because the model is out of the box. Generally, the average time is not more than 200. Please check the number of output bbox.
