### ISSUE TITLE
Could not reproduce the precision on 20% Waymo

### ISSUE THREAD

**Issue by JingweiZhang12** [Haiyang-W/DSVT#29]
Hi, thanks for your source code. I set up the environment according to the guide and  try this training command under this codebase:
```shell
bash scripts/dist_train.sh 8 --cfg_file ./cfgs/dsvt_models/dsvt_plain_D512e.yaml --sync_bn --logger_iter_interval 500
```
The evaluation results are below and could not reach the official reference [precision](https://drive.google.com/file/d/1XoLwwzDUGRRUv0hNeRNBoGwxaibH5KRG/view):
```shell
OBJECT_TYPE_TYPE_VEHICLE_LEVEL_1/AP: 0.7226 
OBJECT_TYPE_TYPE_VEHICLE_LEVEL_1/APH: 0.7177 
OBJECT_TYPE_TYPE_VEHICLE_LEVEL_1/APL: 0.7226 
OBJECT_TYPE_TYPE_VEHICLE_LEVEL_2/AP: 0.6382 
OBJECT_TYPE_TYPE_VEHICLE_LEVEL_2/APH: 0.6337 
OBJECT_TYPE_TYPE_VEHICLE_LEVEL_2/APL: 0.6382 
OBJECT_TYPE_TYPE_PEDESTRIAN_LEVEL_1/AP: 0.7706 
OBJECT_TYPE_TYPE_PEDESTRIAN_LEVEL_1/APH: 0.6910 
OBJECT_TYPE_TYPE_PEDESTRIAN_LEVEL_1/APL: 0.7706 
OBJECT_TYPE_TYPE_PEDESTRIAN_LEVEL_2/AP: 0.6895 
OBJECT_TYPE_TYPE_PEDESTRIAN_LEVEL_2/APH: 0.6164 
OBJECT_TYPE_TYPE_PEDESTRIAN_LEVEL_2/APL: 0.6895 
OBJECT_TYPE_TYPE_SIGN_LEVEL_1/AP: 0.0000 
OBJECT_TYPE_TYPE_SIGN_LEVEL_1/APH: 0.0000 
OBJECT_TYPE_TYPE_SIGN_LEVEL_1/APL: 0.0000 
OBJECT_TYPE_TYPE_SIGN_LEVEL_2/AP: 0.0000 
OBJECT_TYPE_TYPE_SIGN_LEVEL_2/APH: 0.0000 
OBJECT_TYPE_TYPE_SIGN_LEVEL_2/APL: 0.0000 
OBJECT_TYPE_TYPE_CYCLIST_LEVEL_1/AP: 0.7039 
OBJECT_TYPE_TYPE_CYCLIST_LEVEL_1/APH: 0.6915 
OBJECT_TYPE_TYPE_CYCLIST_LEVEL_1/APL: 0.7039 
OBJECT_TYPE_TYPE_CYCLIST_LEVEL_2/AP: 0.6777 
OBJECT_TYPE_TYPE_CYCLIST_LEVEL_2/APH: 0.6658 
OBJECT_TYPE_TYPE_CYCLIST_LEVEL_2/APL: 0.6777 
```
My training log is [here](https://drive.google.com/file/d/1trv3Cgmumt3JC0RbvVrLxEm2Sckh3Y6Y/view?usp=drive_link)
Could you give me some suggestions?

**Comment by Haiyang-W** [comment]
Could you provide the training log with logger_iter_interval(500)? The loss of training is generally stable, and we can compare to see if there is any problem.

At the moment it looks like loss is high and recall is low. Although there will be some fluctuations in 12e, the gap between your results is too large, so there should be some problems.

This issue will continue to be open. If someone has the same problem, please feel free to ask questions here to see if it is a common problem.

**Comment by Haiyang-W** [comment]
Also, is it convenient to provide your environment configuration?

**Comment by Haiyang-W** [comment]
> Hi, thanks for your source code. I set up the environment according to the guide and try this training command under this codebase:
> 
> ```shell
> bash scripts/dist_train.sh 8 --cfg_file ./cfgs/dsvt_models/dsvt_plain_D512e.yaml --sync_bn --logger_iter_interval 500
> ```
> 
> The evaluation results are below and could not reach the official reference [precision](https://drive.google.com/file/d/1XoLwwzDUGRRUv0hNeRNBoGwxaibH5KRG/view):
> 
> ```shell
> OBJECT_TYPE_TYPE_VEHICLE_LEVEL_1/AP: 0.7226 
> OBJECT_TYPE_TYPE_VEHICLE_LEVEL_1/APH: 0.7177 
> OBJECT_TYPE_TYPE_VEHICLE_LEVEL_1/APL: 0.7226 
> OBJECT_TYPE_TYPE_VEHICLE_LEVEL_2/AP: 0.6382 
> OBJECT_TYPE_TYPE_VEHICLE_LEVEL_2/APH: 0.6337 
> OBJECT_TYPE_TYPE_VEHICLE_LEVEL_2/APL: 0.6382 
> OBJECT_TYPE_TYPE_PEDESTRIAN_LEVEL_1/AP: 0.7706 
> OBJECT_TYPE_TYPE_PEDESTRIAN_LEVEL_1/APH: 0.6910 
> OBJECT_TYPE_TYPE_PEDESTRIAN_LEVEL_1/APL: 0.7706 
> OBJECT_TYPE_TYPE_PEDESTRIAN_LEVEL_2/AP: 0.6895 
> OBJECT_TYPE_TYPE_PEDESTRIAN_LEVEL_2/APH: 0.6164 
> OBJECT_TYPE_TYPE_PEDESTRIAN_LEVEL_2/APL: 0.6895 
> OBJECT_TYPE_TYPE_SIGN_LEVEL_1/AP: 0.0000 
> OBJECT_TYPE_TYPE_SIGN_LEVEL_1/APH: 0.0000 
> OBJECT_TYPE_TYPE_SIGN_LEVEL_1/APL: 0.0000 
> OBJECT_TYPE_TYPE_SIGN_LEVEL_2/AP: 0.0000 
> OBJECT_TYPE_TYPE_SIGN_LEVEL_2/APH: 0.0000 
> OBJECT_TYPE_TYPE_SIGN_LEVEL_2/APL: 0.0000 
> OBJECT_TYPE_TYPE_CYCLIST_LEVEL_1/AP: 0.7039 
> OBJECT_TYPE_TYPE_CYCLIST_LEVEL_1/APH: 0.6915 
> OBJECT_TYPE_TYPE_CYCLIST_LEVEL_1/APL: 0.7039 
> OBJECT_TYPE_TYPE_CYCLIST_LEVEL_2/AP: 0.6777 
> OBJECT_TYPE_TYPE_CYCLIST_LEVEL_2/APH: 0.6658 
> OBJECT_TYPE_TYPE_CYCLIST_LEVEL_2/APL: 0.6777 
> ```
> 
> My training log is [here](https://drive.google.com/file/d/1trv3Cgmumt3JC0RbvVrLxEm2Sckh3Y6Y/view?usp=drive_link) Could you give me some suggestions?

I find it. You forgot to turn on syncbn. Maybe you should stick to the script. When batch_size_per_gpu = 1, normal bn is useless, so syncbn must be turned on.

**Comment by JingweiZhang12** [comment]
Thanks for your timely reply. My bad. I used `--sync-bn` rather than `--sync_bn` in the command.

**Comment by Haiyang-W** [comment]
> Thanks for your timely reply. My bad. I used `--sync-bn` rather than `--sync_bn` in the command.

Great! Wish you all the best. :)
