### ISSUE TITLE
Could you report your official performance on waymo test set?

### ISSUE THREAD

**Issue by StiphyJay** [Haiyang-W/DSVT#3]

**Comment by Haiyang-W** [comment]
Thanks for your interest in DSVT.  I am rushing some DDLs. The paper will be updated in a few weeks at most, including the SOTA performance of 3D Object detection on the Waymo test set, NuScenes validation, and test set.  Moreover, the best Bev map segmentation performance on NuScenes will also be provided. 

Best regards,
Haiyang

**Comment by Soul-Go-odman** [comment]
Thanks for your nice work. 
I'd like to know if there will be any experimental results of 3D point cloud semantic segmentation in the future.

**Comment by Haiyang-W** [comment]
> Thanks for your nice work. I'd like to know if there will be any experimental results of 3D point cloud semantic segmentation in the future.

We are working on some 3D point cloud semantic segmentation tasks. There's still some special architecture to be designed, hopefully that goes well. Its better performance of BEV map segmentation  than sparse convolution demonstrate its powerful modeling capacity.

**Comment by Haiyang-W** [comment]
> > Thanks for your nice work. I'd like to know if there will be any experimental results of 3D point cloud semantic segmentation in the future.
> 
> We are working on some 3D point cloud semantic segmentation tasks. There's still some special architecture to be designed, hopefully that goes well. Its better performance of BEV map segmentation than sparse convolution demonstrate its powerful modeling capacity.

Thank you for your inquiry. We appreciate your interest in our products. We will make every effort to introduce DSVT to 3D point clouds semantic segmentation as soon as possible. We kindly ask for your patience in the meantime.

Best regards,
Haiyang
