### ISSUE TITLE
Detection ability drops significantly at long distances

### ISSUE THREAD

**Issue by zizhengu** [Haiyang-W/DSVT#32]
When I used DSVT on my own dataset, I found that it has excellent detection ability for nearby objects (0-30m), but the mean Average Precision drops significantly at long distances (30-60m,60m-inf) compared to Centerpoints model. Can we explain it?

**Comment by Haiyang-W** [comment]
I'm not sure about that. It makes sense that our backbone and sparse conv perform equally well at long and short distances, at least from what we've seen on waymo.  I suspect it's because of your previous parameter error [issue](https://github.com/Haiyang-W/DSVT/issues/27#issue-1731705310).
