### ISSUE TITLE
setup error

### ISSUE THREAD

**Issue by Wang0203** [Haiyang-W/DSVT#35]
> python setup.py develop
> No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
> running develop
> /opt/conda/envs/py37/lib/python3.7/site-packages/setuptools/command/easy_install.py:147: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
>   EasyInstallDeprecationWarning,
> /opt/conda/envs/py37/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
>   setuptools.SetuptoolsDeprecationWarning,
> running egg_info
> creating pcdet.egg-info
> writing pcdet.egg-info/PKG-INFO
> writing dependency_links to pcdet.egg-info/dependency_links.txt
> writing requirements to pcdet.egg-info/requires.txt
> writing top-level names to pcdet.egg-info/top_level.txt
> writing manifest file 'pcdet.egg-info/SOURCES.txt'
> reading manifest file 'pcdet.egg-info/SOURCES.txt'
> adding license file 'LICENSE'
> writing manifest file 'pcdet.egg-info/SOURCES.txt'
> running build_ext
> building 'pcdet.ops.iou3d_nms.iou3d_nms_cuda' extension
> creating /root/workspace/env_run/DSVT/build
> creating /root/workspace/env_run/DSVT/build/temp.linux-x86_64-cpython-37
> creating /root/workspace/env_run/DSVT/build/temp.linux-x86_64-cpython-37/pcdet
> creating /root/workspace/env_run/DSVT/build/temp.linux-x86_64-cpython-37/pcdet/ops
> creating /root/workspace/env_run/DSVT/build/temp.linux-x86_64-cpython-37/pcdet/ops/iou3d_nms
> creating /root/workspace/env_run/DSVT/build/temp.linux-x86_64-cpython-37/pcdet/ops/iou3d_nms/src
> Traceback (most recent call last):
>   File "setup.py", line 133, in <module>
>     'src/ingroup_inds_kernel.cu',
>   File "/opt/conda/envs/py37/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
>     return distutils.core.setup(**attrs)
>   File "/opt/conda/envs/py37/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 177, in setup
>     return run_commands(dist)
>   File "/opt/conda/envs/py37/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 193, in run_commands
>     dist.run_commands()
>   File "/opt/conda/envs/py37/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
>     self.run_command(cmd)
>   File "/opt/conda/envs/py37/lib/python3.7/site-packages/setuptools/dist.py", line 1229, in run_command
>     super().run_command(command)
>   File "/opt/conda/envs/py37/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
>     cmd_obj.run()
>   File "/opt/conda/envs/py37/lib/python3.7/site-packages/setuptools/command/develop.py", line 34, in run
>     self.install_for_development()
>   File "/opt/conda/envs/py37/lib/python3.7/site-packages/setuptools/command/develop.py", line 114, in install_for_development
>     self.run_command('build_ext')
>   File "/opt/conda/envs/py37/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 317, in run_command
>     self.distribution.run_command(command)
>   File "/opt/conda/envs/py37/lib/python3.7/site-packages/setuptools/dist.py", line 1229, in run_command
>     super().run_command(command)
>   File "/opt/conda/envs/py37/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
>     cmd_obj.run()
>   File "/opt/conda/envs/py37/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
>     _build_ext.run(self)
>   File "/opt/conda/envs/py37/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
>     _build_ext.build_ext.run(self)
>   File "/opt/conda/envs/py37/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
>     self.build_extensions()
>   File "/opt/conda/envs/py37/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 708, in build_extensions
>     build_ext.build_extensions(self)
>   File "/opt/conda/envs/py37/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
>     _build_ext.build_ext.build_extensions(self)
>   File "/opt/conda/envs/py37/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 459, in build_extensions
>     self._build_extensions_serial()
>   File "/opt/conda/envs/py37/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 485, in _build_extensions_serial
>     self.build_extension(ext)
>   File "/opt/conda/envs/py37/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
>     _build_ext.build_extension(self, ext)
>   File "/opt/conda/envs/py37/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 547, in build_extension
>     depends=ext.depends,
>   File "/opt/conda/envs/py37/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 524, in unix_wrap_ninja_compile
>     cuda_post_cflags = unix_cuda_flags(cuda_post_cflags)
>   File "/opt/conda/envs/py37/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 423, in unix_cuda_flags
>     cflags + _get_cuda_arch_flags(cflags))
>   File "/opt/conda/envs/py37/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1561, in _get_cuda_arch_flags
>     arch_list[-1] += '+PTX'
> IndexError: list index out of range

**Comment by Haiyang-W** [comment]
please refer this [issue](https://github.com/Haiyang-W/DSVT/issues/16#issue-1670488520).
