### ISSUE TITLE
DynPillarVFE in nuscenes setup

### ISSUE THREAD

**Issue by Flamyx** [Haiyang-W/DSVT#36]
Hello, thank you for releasing nuscenes update!
Could you tell me please whether using DynPillarVFE is right in dsvt_plain_1f_onestage_nusences.yaml? 
In other versions (e.g. for waymo) you used DynPillarVFE3D, so I'm wondering why is it different for nuscenes?

**Comment by Haiyang-W** [comment]
In pillar setting, there's no difference between them. 
PS. there was no significant improvement in DSVT-3D on nuscenes, so we only adopt DSVT-Pillar setting.
