### ISSUE TITLE
Metric results for mini-nuscenes 

### ISSUE THREAD

**Issue by Wang0203** [Haiyang-W/DSVT#37]
Hello, thank you for your excellent work. I am currently limited to do experiments on the mini dataset. Have you done any relevant experiments on the mini-nuscenes and what are the metrics?

**Comment by Haiyang-W** [comment]
Thanks for your interest in our work. 

Sorry for that, we haven't tried mini-nuscenes. You can try kitti. Although we haven't tried it, compatibility with dsvt and kitti via pcdet shouldn't be too difficult.
