### ISSUE TITLE
Congratulations on being accepted by CVPR！ I'm looking forward to your open source code.

### ISSUE THREAD

**Issue by SweetZed** [Haiyang-W/DSVT#4]

**Comment by Haiyang-W** [comment]
Thanks very much. We are working on code refactor and  will release it at most end of March, including the SOTA performance of Waymo LiDAR Object Detection, NuScenes LiDAR Object Detection and BEV Map Segmentation.  :)

**Comment by Haiyang-W** [comment]
Code has been released.
