### ISSUE TITLE
DSVT Voxel Performance using 100% waymo dataset

### ISSUE THREAD

**Issue by ylwhxht** [Haiyang-W/DSVT#41]
Hi,

I trained a DSVT model using the Waymo dataset with batch_size = 3 and 3 3090 GPUs(with torch.utils.checkpoints). The performance of mAP/H is about 1% below your benchmark. 
Especially in the Ped. is particularly severe, but on the contrary, there are some improvements in the L2 of Vehicle.

[my log](https://paste.imlgw.top/2332)

**Comment by chenshi3** [comment]
The reported performance is obtained with a batch_size of 3 and 8 GPUs.
