### ISSUE TITLE
Deploy Problem 2

### ISSUE THREAD

**Issue by sylcito** [Haiyang-W/DSVT#42]
Hi, thanks your great work!
Another question about Pytorch-ONNX-TensorRT conversion. 

In the forward function of SetAttention, indexing is used at the beginning to retrieve values. However, when deploying similar operations, TensorRT does not support this because the indices are also a changing tensor, rather than fixed indices like x=torch.tensor([1, 2]), x[0]. How did you solve this in your TensorRT engine? Could you please provide some guidance?

https://github.com/Haiyang-W/DSVT/blob/3b825d11e7695d514d795457771508859a44a08b/pcdet/models/backbones_3d/dsvt.py#L245

Wish your reply.

**Comment by chenshi3** [comment]
You need to specify the dynamic shape in Pytorch-ONNX-TensorRT conversion.

**Comment by sylcito** [comment]
> You need to specify the dynamic shape in Pytorch-ONNX-TensorRT conversion.

Same as this?
https://github.com/Haiyang-W/DSVT/blob/3b825d11e7695d514d795457771508859a44a08b/tools/deploy.py#L194

**Comment by chenshi3** [comment]
Yep. You should to specify it in the trtexec command as well.
