### ISSUE TITLE
Can you provide a configuration file for the KITTI dataset?

### ISSUE THREAD

**Issue by Rocklei-pu** [Haiyang-W/DSVT#44]
This is a great work, but there are no experiments conducted on the KITTI dataset in the paper. I would like to validate the performance of DSVT on the KITTI dataset. Could you please provide a configuration file for DSVT on the KITTI dataset?

**Comment by Haiyang-W** [comment]
> This is a great work, but there are no experiments conducted on the KITTI dataset in the paper. I would like to validate the performance of DSVT on the KITTI dataset. Could you please provide a configuration file for DSVT on the KITTI dataset?

I'm sorry, we didn't try it on the kitti dataset. However, I think you can easily run on kitti based on pcdet, just change some corresponding pillar size and point cloud range. The performance can refer to the kitti performance of [MsSVT](https://openreview.net/pdf?id=hOVEBHpHrMu), which should be better than it.
