### ISSUE TITLE
IndexError in test using nuscenes

### ISSUE THREAD

**Issue by cjfghddl0206** [Haiyang-W/DSVT#45]
After training was completed using 3090x3 and it took 9 to 10 days, the evaluation did not run and stopped in the middle at epoch 20. After the value came out as shown in the photo, after loading 6019 data in the data val, loading the groud truth and filtering the prediction, an index error appeared.
![Screenshot from 2023-07-07 17-54-47](https://github.com/Haiyang-W/DSVT/assets/87977123/1b81737e-ede1-45b7-9954-8cbbca1c1c47)

**Comment by Haiyang-W** [comment]
Please try to run the inference code first based on our pretrained model [weight](https://drive.google.com/file/d/10d7c-uJxg5w4GN-JmRBQi4gQDwHiOHxP/view).  If the performance can match the scores reported in our paper, it means that there is no problem with the data processing.

**Comment by Haiyang-W** [comment]
> After training was completed using 3090x3 and it took 9 to 10 days, the evaluation did not run and stopped in the middle at epoch 20. After the value came out as shown in the photo, after loading 6019 data in the data val, loading the groud truth and filtering the prediction, an index error appeared. ![Screenshot from 2023-07-07 17-54-47](https://user-images.githubusercontent.com/87977123/251691920-1b81737e-ede1-45b7-9954-8cbbca1c1c47.png)

BTW, your training is too slow, the whole training process should be around 1-2 days.

**Comment by cjfghddl0206** [comment]
> > After training was completed using 3090x3 and it took 9 to 10 days, the evaluation did not run and stopped in the middle at epoch 20. After the value came out as shown in the photo, after loading 6019 data in the data val, loading the groud truth and filtering the prediction, an index error appeared. ![Screenshot from 2023-07-07 17-54-47](https://user-images.githubusercontent.com/87977123/251691920-1b81737e-ede1-45b7-9954-8cbbca1c1c47.png)
> 
> BTW, your training is too slow, the whole training process should be around 1-2 days.

Isn't it slow because I use three rtx3090 gpu instead of a100?

**Comment by Haiyang-W** [comment]
> > > After training was completed using 3090x3 and it took 9 to 10 days, the evaluation did not run and stopped in the middle at epoch 20. After the value came out as shown in the photo, after loading 6019 data in the data val, loading the groud truth and filtering the prediction, an index error appeared. ![Screenshot from 2023-07-07 17-54-47](https://user-images.githubusercontent.com/87977123/251691920-1b81737e-ede1-45b7-9954-8cbbca1c1c47.png)
> > 
> > 
> > BTW, your training is too slow, the whole training process should be around 1-2 days.
> 
> Isn't it slow because I use three rtx3090 gpu instead of a100?

I mean rtx 3090 is only 1 day.

**Comment by Haiyang-W** [comment]
This issue seems to have been solved and will be closed.
