### ISSUE TITLE
TensorRT Deployment for nuScenes Trained Model

### ISSUE THREAD

**Issue by yusufy1ld1z** [Haiyang-W/DSVT#46]
Hi, thanks for a great job!
I am having trouble converting the weights of the model trained with nuScenes dataset. As I understand, the deploy.py file only works with Waymo compatibility, and the nuScenes trtengine config yaml is not released. I have tried to write the nuScenes trtengine config file by just replacing the BACKBONE_3D part of the yaml, but before coming to this stage I had other problems with deploy.py. The input data (batch_dict) given by you is Waymo data and I think it is not a solution to just change this data with nuScenes because input_shapes and dynamic_axes config must be changed for nuScenes compatibility. So, is there a way to convert models trained with nuScenes to TensorRT right now, can I resolve this by myself? Are you planning to release some dataset-diagnostic deploy code in the near future?

**Comment by Haiyang-W** [comment]
> Hi, thanks for a great job! I am having trouble converting the weights of the model trained with nuScenes dataset. As I understand, the deploy.py file only works with Waymo compatibility, and the nuScenes trtengine config yaml is not released. I have tried to write the nuScenes trtengine config file by just replacing the BACKBONE_3D part of the yaml, but before coming to this stage I had other problems with deploy.py. The input data (batch_dict) given by you is Waymo data and I think it is not a solution to just change this data with nuScenes because input_shapes and dynamic_axes config must be changed for nuScenes compatibility. So, is there a way to convert models trained with nuScenes to TensorRT right now, can I resolve this by myself? Are you planning to release some dataset-diagnostic deploy code in the near future?

Thanks for your interesting in our work! 
- We currently have no plans to open source deployment versions of the nuscenes version (maybe in the future).
- I recommend you first try waymo deployment to familiarize the tensorRT deployment process. Deployment is not a simple matter. 
- If you only need to deploy backbone3D for Nuscenes, I think it's an easy thing. You just need to modify the deploy.py.

**Comment by Haiyang-W** [comment]
NuScenes Deployment of DSVT will be released in our new paper (Unified multi-modal DSVT), which is accepted by ICCV2023. Please be patient.
