### ISSUE TITLE
param

### ISSUE THREAD

**Issue by Wang0203** [Haiyang-W/DSVT#48]
<img width="306" alt="image" src="https://github.com/Haiyang-W/DSVT/assets/65695245/2f6cfaea-46dc-4ca1-bf50-40ddf01e0834">
<img width="592" alt="image" src="https://github.com/Haiyang-W/DSVT/assets/65695245/bf0e101d-e39f-4d90-9f53-dfe4488ae0f5">
71M in your paper, however 7.1M in code?

**Comment by Wang0203** [comment]
71M in your paper, however 7.1M in code?

**Comment by chenshi3** [comment]
> 71M in your paper, however 7.1M in code?

？？？？？？
1M = 10e6

**Comment by chenshi3** [comment]
My apologies for the oversight. I have identified an error in my calculations, where the number of parameters was inadvertently magnified by a factor of ten.

**Comment by chenshi3** [comment]
> My apologies for the oversight. I have identified an error in my calculations, where the number of parameters was inadvertently magnified by a factor of ten.

This miscalculation affects all parameter computations presented in the paper.

**Comment by chenshi3** [comment]
> Therefore, the number of parameters is 7.1M?

Yes. And the number of parameter of ResBackbone1x is 8.8M.
