### ISSUE TITLE
Confusion about Figure 1 in paper

### ISSUE THREAD

**Issue by StiphyJay** [Haiyang-W/DSVT#5]
Congratulations for accepted in CVPR! I have a problem with Fig. 1. In your paper, your method is evaluated on an NVIDIA A100 GPU. But for other methods, you also evaluated them on A100 GPU? Especially for PointPillars, and CenterPoint-Pillar. Did you also evaluate their speed at the same A100 GPU device? The CenterPoint-Pillar's speed is only 30FPS, which seems strange. A100 has a higher computing power.

**Comment by Haiyang-W** [comment]
All the experiments are evaluated on the same workstation (an NVIDIA A100 GPU with AMD EPYC 7513 CPU). We just follow the implementation of OpenPCDet[centerpoint-pillar](https://github.com/open-mmlab/OpenPCDet/blob/master/tools/cfgs/waymo_models/centerpoint_pillar_1x.yaml). Its inference time contains PillarVFE(cpu) + backbone2D + centerhead + nms.

**Comment by StiphyJay** [comment]
Another problem: Do you use fade strategy during training process?

**Comment by JJangD** [comment]
Hello I have a question about inference speed.  I have a notebook with GPU 3080Ti and evaluated inference time of OpenPCDet implmentaion centerpoint-voxelnet and centepoint-pillar which showed me 30 ms and 70 ms respectively. I expected that centerpoint-pillar would be faster but the result was opposite. Is there any thing I should consider testing inference speed of centerpoint-pillar?
