### ISSUE TITLE
DSVT all in tensorRT

### ISSUE THREAD

**Issue by jingyue202205** [Haiyang-W/DSVT#52]
I implemented DSVT using the Tensorrt API and plugin！ If anyone is interested,  the repository  is (https://github.com/jingyue202205/DSVT-AI-TRT)

**Comment by Haiyang-W** [comment]
> I implemented DSVT using the Tensorrt API and plugin！ If anyone is interested, the repository is (https://github.com/jingyue202205/DSVT-AI-TRT)

Your tremendously valuable efforts are greatly appreciated. In all honesty, deployment isn't our forte. Your assistance, however, will undoubtedly simplify the deployment process for DSVT, making the onboarding of the Transformer much smoother. 

We also extend an invitation for you to stay tuned to our latest work UniTR (https://github.com/Haiyang-W/UniTR). This advancement takes DSVT into the realm of multi-modal 3D perception and introduces weight-sharing among multiple modes. It's the **First Unified Multi-modal Transformer Backbone** for 3D Perception. We're actively working on it and aiming to release the code before ICCV. 

`DSVT` and `UniTR` might serve as preliminary steps towards the development of a foundation model for autonomous driving perception. With your invaluable support, I am confident we are moving in the right direction. 

Thanks for your effort once again :). 

Haiyiang,
