### ISSUE TITLE
DSVT tensorrt model slower than pytorch

### ISSUE THREAD

**Issue by realwenpeng** [Haiyang-W/DSVT#53]
Thanks for your great job!!!
test on A30 GPU
DSVT-pytroch 20.03ms, DSVT-trt 69ms
I think it may because of the dynamic shape setting when tranfer onnx to engine.
I want to know how to get the optimal dynamic shape of the trtexec operation on my own datasets.

**Comment by chenshi3** [comment]
The dynamic shapes in this implementation are based on the statistics of the Waymo-validation-set, which may not be optimal for your own datasets. Additionally, I recommend testing on fixed shapes in a single scene to identify and eliminate any other potential bugs.

**Comment by realwenpeng** [comment]
Thanks, I would try....
