### ISSUE TITLE
DSVT: self-attention key_padding_mask dtype

### ISSUE THREAD

**Issue by d33dler** [Haiyang-W/DSVT#54]
In `class Stage_ReductionAtt_Block` you use key_padding_mask Tensor with dtype = int32, I assume you expect torch to cast it automatically to bool? This behavior has changed in torch==2.0.0 and now throws an error (AssertionError: only bool and floating types of key_padding_mask are supported) , please update the code accordingly.
```
    def forward(self, x, key_padding_mask):
        # x: [voxel_num, c_dim, pool_volume]
        src = self.query_func(x).permute(0, 2, 1)  # voxel_num, 1, c_dim
        key = value = x.permute(0, 2, 1)
        key = key + self.pos_embedding.unsqueeze(0).repeat(src.shape[0], 1, 1)
        query = src.clone()
        output = self.self_attn(query, key, value, key_padding_mask)[0]
        src = self.norm(output + src).squeeze(1)
        return src
```

**Comment by Haiyang-W** [comment]
Thank you very much for pointing out the bug, we will correct it accordingly. 
Thanks a lot! 

Haiyang

**Comment by Haiyang-W** [comment]
Can I ask if you can run directly on pytorch 2.0.0 if you fix this bug? (Sorry, I haven't tried pytorch 2.0 yet)

**Comment by d33dler** [comment]
Only tried a few training iterations in the epoch to see if it runs, it ran well on a single gpu.

**Comment by Haiyang-W** [comment]
> Only tried a few training iterations in the epoch to see if it runs, it ran well on a single gpu.

Great! Thanks for your reply.

**Comment by YoushaaMurhij** [comment]
@d33dler, @Haiyang-W . I tried` BoolTensor()` and `bool()` method to convert `pool_volume`. But the same error keeps showing. Could you please post  a fix for this issue?

Thanks!
