### ISSUE TITLE
Do you use fade strategy during training process?

### ISSUE THREAD

**Issue by StiphyJay** [Haiyang-W/DSVT#6]
It seems that the performance of cyclists class in your paper is higher than that of pedestrians and vehicles? But there are more sample sizes for vehicle(4352210) and pedestrian(2037627) categories, while cyclists only have 49518 samples in the waymo training dataset, which doesn't seem reasonable. Did you use the fade strategy during your training process?

**Comment by chenshi3** [comment]
Following [FSD](https://arxiv.org/pdf/2207.10035.pdf), fade strategy is used during training process which brings +1.0 L2 mAPH gain on _Cyclist_. The fade strategy is a common trick in Waymo and Nuscenes, and we will incorporate it in camera ready version if necessary.

**Comment by Haiyang-W** [comment]
Thank you, @chenshi3,  for the quick reply.  @StiphyJay  If you have any questions, please feel free to reach out to us. :)

Haiyang,

**Comment by StiphyJay** [comment]
> 

Thanks for your reply! It is necessary to report the performance with and without fade strategy. Especially for different categories. Fade strategy usually brings improvement in all categories.

**Comment by Haiyang-W** [comment]
Thanks for your good suggestions.  However, considering paper space limitations (8 pages in camera-ready) and additional experiments on other datasets will be added (SOTA performance on NuScenes with a remarkable gain), we will not include this result in the main paper,  but we will mention that fade strategy was used. The corresponding results (without the fade) will also be released in this repo. Actually, it's a common trick used in all SOTA nuscenes and Waymo approaches, such as BEVFusion, Transfusion and FSD.  Moreover, in our experiments, the fade strategy only worked on cyclists(+1.0). Pedestrians will go up a little(+0.5), and hardly be any improvement in the Veh(+0.1~0.2).

Hope that can ease your concern!

Best regards,
Haiyang

**Comment by Haiyang-W** [comment]
> Thanks for your good suggestions. However, considering paper space limitations (8 pages in camera-ready) and additional experiments on other datasets will be added (SOTA performance on NuScenes with a remarkable gain), we will not include this result in the main paper, but we will mention that fade strategy was used. The corresponding results (without the fade) will also be released in this repo. Actually, it's a common trick used in all SOTA nuscenes and Waymo approaches, such as BEVFusion, Transfusion and FSD. Moreover, in our experiments, the fade strategy only worked on cyclists(+1.0). Pedestrians will go up a little(+0.5), and hardly be any improvement in the Veh(+0.1~0.2).
> 
> Hope that can ease your concern!
> 
> Best regards, Haiyang

We will consider your valuable advice. Maybe we can add it to the appendix. Thanks for your good suggestions again, which make our paper more substantial. :)

Best regards,
Haiyang

**Comment by StiphyJay** [comment]
Thanks for your reply!  

Best regards!
