### ISSUE TITLE
Nuscenes train

### ISSUE THREAD

**Issue by 123susu** [Haiyang-W/DSVT#65]
Full Nuscenes dataset have 10 part,l want ask a question:when l load first part and train it,what should l do next? load second part and train?and so on until 10 part train done?

**Comment by Haiyang-W** [comment]
Please follow the dataset generation instruction in [OpenPCDet](https://github.com/open-mmlab/OpenPCDet/blob/master/docs/GETTING_STARTED.md#nuscenes-dataset). After preprocessing the nuscenes tars, there will be only one part. Then run the training code we provided [here](https://github.com/Haiyang-W/DSVT#training).
