### ISSUE TITLE
Question about the setting of voxel version

### ISSUE THREAD

**Issue by 3bobo** [Haiyang-W/DSVT#67]
Thanks for your great work! However, the setting of the voxel version confused me.
https://github.com/Haiyang-W/DSVT/blob/a0ab685b573896fc4bc9a64b187bdc2b574c3741/tools/cfgs/dsvt_models/dsvt_3D_1f_onestage.yaml#L78

Each stage only has 1 block. Therefore, for each stage, it can only use non-shift or shift, not both. For example, in stage-0, the block only uses the window ``[12, 12,  32]`` with shift ``[0, 0, 0]`` X and Y ``set_voxel_inds``. But in stage-1, the block only uses the window ``[24, 24  8]`` with shift ``[6, 6, 0]`` X and Y ``set_voxel_inds``. Therefore, within each stage, is there no shift and hybrid setting to propagate the inter-window feature?

**Comment by chenshi3** [comment]
Yes, there is no shift and hybrid setting within one stage. However, shift window between stages can still provide global receptive field.

**Comment by 3bobo** [comment]
Thanks for your reply!
