### ISSUE TITLE
dsvt export

### ISSUE THREAD

**Issue by yumendecc** [Haiyang-W/DSVT#69]
您好，deploy.py设置了动态维度导出的onnx文件，nn.MultiheadAttention模块会产生大量Unsqueeze、Cast算子，请问关于这个问题有什么好的方法或者优化思路提供吗？
以下是分别使用动态维度和固定维度导出nn.MultiheadAttention的onnx
![22](https://github.com/Haiyang-W/DSVT/assets/45125415/e1e55e01-7192-4c87-b0b4-b58ce2de55e1)
![11](https://github.com/Haiyang-W/DSVT/assets/45125415/900658da-bc6c-4eef-8962-5e1bcf94cee7)

**Comment by chenshi3** [comment]
之前想过一个思路，设置一个固定值，大于这个的通过一些手段把他的数量downsample下来，小于这个的做一些padding，但不确定对性能和速度的影响。
