### ISSUE TITLE
兄弟，你们那个68.4用了tta了吗

### ISSUE THREAD

**Issue by rubbish001** [Haiyang-W/DSVT#70]

**Comment by chenshi3** [comment]
没用，一把跑出来的

**Comment by rubbish001** [comment]
最后提交的权重在val精度多少 ，NDS：84？ ，mAP 88？

**Comment by chenshi3** [comment]
我当时跑出来后，pcdet会生成一个文件，直接提交了，没在val上测过

**Comment by rubbish001** [comment]
牛，我跑了一个比你低一点的结果，但是tta效果很差，哎

**Comment by rubbish001** [comment]
删除这个帖子把

**Comment by chenshi3** [comment]
> Author

说实话，我在waymo上试过tta，不好用

**Comment by chenshi3** [comment]
> 牛，我跑了一个比你低一点的结果，但是tta效果很差，哎

当时不知道自己哪里没弄

**Comment by rubbish001** [comment]
算了，先水一篇出去在说，我刚刷出来的

**Comment by chenshi3** [comment]
> 删除这个帖子把

等一下仓库主人，我不是owner，没权限
