### ISSUE TITLE
Question about multi_frame training in Waymo

### ISSUE THREAD

**Issue by YoushaaMurhij** [Haiyang-W/DSVT#72]
Question: How to train 3D model using multi_frame config on Waymo dataset?
I prepared the data for multi_frame training using :
```bash
python -m pcdet.datasets.waymo.waymo_dataset --func create_waymo_infos \
    --cfg_file tools/cfgs/dataset_configs/waymo_dataset_multiframe.yaml
```
But, I am not sure if only setting   _BASE_CONFIG_: cfgs/dataset_configs/waymo_dataset_multiframe.yaml is enough to do the job! And how to select how many frames  ot be used?

Thanks!

**Comment by chenshi3** [comment]
you can adjust the selected frames according this key: 
[TIME_RANGE: [0.3, 0.0]  # 0.3s-0.0s indicates 4 frames ](https://github.com/Haiyang-W/DSVT/blob/81f4b9ec95104dde04f57d61330a6ba3af4250dc/tools/cfgs/dataset_configs/waymo_dataset_multiframe.yaml#L55C11-L55C66)

**Comment by chenshi3** [comment]
keep [FILTER_OBJ_POINTS_BY_TIMESTAMP = True](https://github.com/Haiyang-W/DSVT/blob/81f4b9ec95104dde04f57d61330a6ba3af4250dc/tools/cfgs/dataset_configs/waymo_dataset_multiframe.yaml#L54C11-L54C48)

**Comment by YoushaaMurhij** [comment]
It is already True. I am actuallly using your default config files
