### ISSUE TITLE
About Model Params

### ISSUE THREAD

**Issue by ygy123first** [Haiyang-W/DSVT#74]
hello，I want to know why the parameters in your paper is 71M, but the code shows the parameters is 7.1M.(in the dsvt_plain_1f_onestage_nusences.yaml)
![R8TX1@YO9FPIVL4}Q6@EN9M](https://github.com/Haiyang-W/DSVT/assets/133750309/7378e45a-0de9-4846-a4f2-812b956c194e)
![B{GKPBXCJ9~4ENETHR`8I70](https://github.com/Haiyang-W/DSVT/assets/133750309/88e7e988-9abb-4cf0-8ce8-61731c9a5649)
Thanks!

**Comment by chenshi3** [comment]
Hi,
My apologies for the oversight. I have identified an error in my calculations, where the number of parameters was inadvertently magnified by a factor of ten. This miscalculation affects all parameter computations presented in the paper.
