### ISSUE TITLE
Questions about voxels?

### ISSUE THREAD

**Issue by git-xuefu** [Haiyang-W/DSVT#78]
How do I convert point clouds into voxel features?  Where is the Voxel Feature Encoder involved in the code?

**Comment by chenshi3** [comment]
Here:
https://github.com/Haiyang-W/DSVT/blob/8cfc2a6f23eed0b10aabcdc4768c60b184357061/pcdet/datasets/processor/data_processor.py#L120

**Comment by git-xuefu** [comment]
> Here:
> 
> https://github.com/Haiyang-W/DSVT/blob/8cfc2a6f23eed0b10aabcdc4768c60b184357061/pcdet/datasets/processor/data_processor.py#L120

Thank you for your reply!
