### ISSUE TITLE
Detail about the VFE module

### ISSUE THREAD

**Issue by yipliu** [Haiyang-W/DSVT#8]
Hi,

Since I'm new to this field, I didn't understand `the voxel feature encoding` (VFE) module very easily.

It seems that this module (VFE) is a common structure, can you please elaborate on it?

> Is it voxelnet or pointpillars?

**Comment by Haiyang-W** [comment]
Yes, it's a common structure. We adopt the dynamic vfe adopted in Pointpillar with pillar size (0.32, 0.32).
