### ISSUE TITLE
NaN problem

### ISSUE THREAD

**Issue by lyhnsn** [Haiyang-W/DSVT#80]
Dear author, I noticed that you mentioned "You can train the model with fp16 setting to save cuda memory, which may occasionally report gradient NaN error."

I also met this problem in my own code and I checked and confirmed the data type in my code was just float16.

I wonder why this can happen. Hope your reply. Thank you!

**Comment by Haiyang-W** [comment]
I also occasionally encounter this issue, but if you use my code, this problem shouldn't occur often, right? However, if you're using a transfusion head and FP16, NaN values are more likely to appear. Otherwise, the chances of it happening should be low.

**Comment by lyhnsn** [comment]
All right. Thank you!
