### ISSUE TITLE
Data preparation, weights and TRT deployment

### ISSUE THREAD

**Issue by YoushaaMurhij** [Haiyang-W/DSVT#9]
Thanks for sharing this amazing work!
Could you please provide the steps to generate gt data from Waymo original dataset?
Are you willing to provide the pertained models if the user sends his agreement to Waymo dataset licence?
Do you plan to publish a sample deployment script to TRT?

Thanks

**Comment by Haiyang-W** [comment]
Thanks for your interests! 
- We use the same data generation as OpenPCDet, so you can follow the [GetStart](https://github.com/open-mmlab/OpenPCDet/blob/master/docs/GETTING_STARTED.md) for more details of data processing. 
- As for the model sharing, actually I'm not familiar with it and only know that waymo weights are generally not shared due to the licence limitation.  However I believe you can easily achieve the performance reported in our paper by the released codes. Moreover, we also provide the training log of all the experiments for easy reproduction.
- Deployment code is a bit complex and detailed, and we probably won't share it. Very sorry for that.

Hope that can ease your concerns.

Haiyang

**Comment by Haiyang-W** [comment]
> Thanks for sharing this amazing work! Could you please provide the steps to generate gt data from Waymo original dataset? Are you willing to provide the pertained models if the user sends his agreement to Waymo dataset licence? Do you plan to publish a sample deployment script to TRT?
> 
> Thanks

Deployment is a highly intricate process that involves multiple steps and procedures. However, if you require the TRT code urgently, we can provide you with a relatively unrefined version. Regarding the model weights, we would be delighted to share them with you upon receipt of the Waymo dataset license agreement.

Best regrads,
Haiyang

**Comment by Haiyang-W** [comment]
> @Haiyang-W Funny you say _"Deployment code is a bit complex and detailed"_ yet in the paper you mention _"[...] DSVT can be easily deployed by TensorRT with real-time inference speed (27Hz) "_ . In any case at least some directives would be nice. Nevertheless good work.

Although deployment is a complex and detailed process that requires multiple steps and procedures,  if you require it urgently, we would be happy to assist you, such as providing a relatively unrefined version of TRT codes.  Please let us know how we can best support you.

Best regards,
Haiyang

**Comment by Haiyang-W** [comment]
The main reason why the TRT code has not been released is because the deployment process is complex and involves multiple human interventions, which are not directly related to our method. We also want to maintain the cleanliness of our code. 

If someone wants to deploy, you can follow the official TensorRT deployment process to complete the steps.

- torch->onnx: https://pytorch.org/docs/stable/onnx.html
- onnx->tensorrt: https://developer.nvidia.com/zh-cn/blog/tensorrt-trtexec-cn/

If anyone wants the original unrefined deployment codes, please send me an email.

Best,
Haiyang

**Comment by YoushaaMurhij** [comment]
> The main reason why the TRT code has not been released is because the deployment process is complex and involves multiple human interventions, which are not directly related to our method. We also want to maintain the cleanliness of our code.
> 
> If someone wants to deploy, you can follow the official TensorRT deployment process to complete the steps.
> 
> * torch->onnx: https://pytorch.org/docs/stable/onnx.html
> * onnx->tensorrt: https://developer.nvidia.com/zh-cn/blog/tensorrt-trtexec-cn/
> 
> If anyone wants the original unrefined deployment codes, please send me an email.
> 
> Best, Haiyang

I have sent an email. Is it still possible to get the deployment code?
Thanks

**Comment by dinvincible98** [comment]
@Haiyang-W Hi, can I get a unrefined deployment code for reference? This is my email: mingqingyuan98@gmail.com. Thank you!

**Comment by Haiyang-W** [comment]
> @Haiyang-W Hi, can I get a unrefined deployment code for reference? This is my email: [mingqingyuan98@gmail.com](mailto:mingqingyuan98@gmail.com). Thank you!

I have emailed it to you. We are working on writing some docs of TensorRT to guide DSVT deployment. Please be patient. We'll release it soon.

**Comment by zizhengu** [comment]
I have tried a DSVT model and want to further deploy it for it's amazing performance. Can I get a unrefined deployment code for reference? This is my email: [zizhengu@163.com]. Thank you very much!

**Comment by zizhengu** [comment]
I have trained a DSVT model and want to further deploy it for it's amazing performance. Can I get a unrefined deployment code for reference? This is my email: [[zizhengu@163.com](mailto:zizhengu@163.com)]. Thank you very much!

**Comment by LinuxCup** [comment]
I tried to deploy, but failed which TensorRT not support some torch operators directly. Can I get your deployment codes? if so, email: 1321504124@qq.com. 
thx

**Comment by Haiyang-W** [comment]
> The unrefined version has been emailed. :)

The unrefined version has been emailed. :)

Haiyang

**Comment by Haiyang-W** [comment]
> I tried to deploy, but failed which TensorRT not support some torch operators directly. Can I get your deployment codes? if so, email: [1321504124@qq.com](mailto:1321504124@qq.com). thx

The unrefined version has been emailed. :)
Haiyang

**Comment by superpigforever** [comment]
Hi, can you share the deployment codes? My email: sw3197@nyu.edu

**Comment by superpigforever** [comment]
> > [sw3197@nyu.edu](mailto:sw3197@nyu.edu)
> 
> The unrefined version has been emailed. :)

Hi
I'm sorry, the attachment is removed by the filter. can you resend the attachment to the following email:

[wsy1301145977@gmail.com](mailto:wsy1301145977@gmail.com)

**Comment by Haiyang-W** [comment]
> > > [sw3197@nyu.edu](mailto:sw3197@nyu.edu)
> > 
> > 
> > The unrefined version has been emailed. :)
> 
> Hi I'm sorry, the attachment is removed by the filter. can you resend the attachment to the following email:
> 
> [wsy1301145977@gmail.com](mailto:wsy1301145977@gmail.com)

Have resent it.

**Comment by Haiyang-W** [comment]
> @Haiyang-W Thanks for your nice work! Could you please share the unrefined deployment code? Thank you. My email: [ihaohe@hotmail.com](mailto:ihaohe@hotmail.com)

We have released the TRT code of backbone3D (DSVT), please refer [here](https://github.com/Haiyang-W/DSVT#tensorrt-deployment).

**Comment by gauthamnarayan** [comment]
@Haiyang-W Thank you very much for your work and for releasing the partial deployment code for backbone 3d in tensorrt. It would be really helpful if you can share the unrefined full deployment code to tecplot123@gmail.com. Thanks a lot for this!

**Comment by Haiyang-W** [comment]
> @Haiyang-W Thank you very much for your work and for releasing the partial deployment code for backbone 3d in tensorrt. It would be really helpful if you can share the unrefined full deployment code to [tecplot123@gmail.com](mailto:tecplot123@gmail.com). Thanks a lot for this!

Have already sent. Wish you all the best!

**Comment by ihaohe** [comment]
> > @Haiyang-W Thank you very much for your work and for releasing the partial deployment code for backbone 3d in tensorrt. It would be really helpful if you can share the unrefined full deployment code to [tecplot123@gmail.com](mailto:tecplot123@gmail.com). Thanks a lot for this!
> 
> Have already sent. Wish you all the best!
Thanks again for releasing the partial deployment code. I've the same need of  the **unrefined full deployment code**. It would be very helpful if you send to [ihaohe@hotmail.com](mailto:ihaohe@hotmail.com).

**Comment by ihaohe** [comment]
> > @Haiyang-W Thank you very much for your work and for releasing the partial deployment code for backbone 3d in tensorrt. It would be really helpful if you can share the unrefined full deployment code to [tecplot123@gmail.com](mailto:tecplot123@gmail.com). Thanks a lot for this!
> 
> Have already sent. Wish you all the best!

Thanks again for releasing the partial deployment code. I've the same need of the **unrefined full deployment code**. It would be very helpful if you send the code to [ihaohe@hotmail.com](mailto:ihaohe@hotmail.com).

**Comment by Haiyang-W** [comment]
> > > @Haiyang-W Thank you very much for your work and for releasing the partial deployment code for backbone 3d in tensorrt. It would be really helpful if you can share the unrefined full deployment code to [tecplot123@gmail.com](mailto:tecplot123@gmail.com). Thanks a lot for this!
> > 
> > 
> > Have already sent. Wish you all the best!
> 
> Thanks again for releasing the partial deployment code. I've the same need of the **unrefined full deployment code**. It would be very helpful if you send the code to [ihaohe@hotmail.com](mailto:ihaohe@hotmail.com).

Have already sent it. :)

**Comment by mincheoree** [comment]
> @Haiyang-W Thank you very much for your work and for releasing the partial deployment code for backbone 3d in tensorrt. It would be really helpful if you can share the unrefined full deployment code to [tecplot123@gmail.com](mailto:tecplot123@gmail.com). Thanks a lot for this!

@Haiyang-W Thanks for your amazing works on releasing DSVT! Thanks for releasing the partial deployment codes. I also have the same need of unrefined full deployment code. It would be really helpful if you can share the unrefined full deployment codes to mincheoljang522@gmail.com. Thanks a lot for sharing!

**Comment by Haiyang-W** [comment]
> > @Haiyang-W Thank you very much for your work and for releasing the partial deployment code for backbone 3d in tensorrt. It would be really helpful if you can share the unrefined full deployment code to [tecplot123@gmail.com](mailto:tecplot123@gmail.com). Thanks a lot for this!
> 
> @Haiyang-W Thanks for your amazing works on releasing DSVT! Thanks for releasing the partial deployment codes. I also have the same need of unrefined full deployment code. It would be really helpful if you can share the unrefined full deployment codes to [mincheoljang522@gmail.com](mailto:mincheoljang522@gmail.com). Thanks a lot for sharing!

Have already sent it. :)

**Comment by d33dler** [comment]
@Haiyang-W could you send the unrefined full deployment as well? Thank you!
r.rebeja@student.rug.nl

**Comment by Haiyang-W** [comment]
> r.rebeja@student.rug.nl

Have sent it :)

**Comment by cyhasuka** [comment]
Hello,
Thanks again for releasing the partial deployment code. 
I have trained a DSVT model with nuscenes and want to further deploy it. It would be very helpful if you send the code to [cyhasuka@gmail.com](cyhasuka@gmail.com).
Thank you and wish you all the best!

**Comment by Haiyang-W** [comment]
> Hello, Thanks again for releasing the partial deployment code. I have trained a DSVT model with nuscenes and want to further deploy it. It would be very helpful if you send the code to [cyhasuka@gmail.com](cyhasuka@gmail.com). My Google account above has already been registered with Waymo's official platform, and have agreed to the Waymo dataset license. If you can provide a pre-trained model to me, I would greatly appreciate it. Thank you and wish you all the best!

The unrefined full deployment code of DSVT-waymo (centerhead) has been sent to your mailbox. Nuscenes is the Transfusion head version, which I'm sure shouldn't be too hard.

**Comment by gcunhase** [comment]
Hi @Haiyang-W could you please share the unrefined full deployment codes to [gwena.cs@gmail.com](mailto:gwena.cs@gmail.com) as well please? Can you also please direct me to the `batch_dict.pth` file? Thanks.

**Comment by Haiyang-W** [comment]
Have sent it. :) 


But I suggest you use the deployment code in the repo to deploy, or this [repo](https://github.com/jingyue202205/DSVT-AI-TRT).

**Comment by Haiyang-W** [comment]
> Hi @Haiyang-W could you please share the unrefined full deployment codes to [gwena.cs@gmail.com](mailto:gwena.cs@gmail.com) as well please? Can you also please direct me to the `batch_dict.pth` file? Thanks.

Have sent it. :) 


But I suggest you use the deployment code in the repo to deploy, or this [repo](https://github.com/jingyue202205/DSVT-AI-TRT).
